package cn.xpu.dao;

import java.util.List;

import cn.xpu.dataobject.ItemDO;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Sep 04 20:23:08 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Sep 04 20:23:08 GMT+08:00 2019
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Sep 04 20:23:08 GMT+08:00 2019
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Sep 04 20:23:08 GMT+08:00 2019
     */
    ItemDO selectByPrimaryKey(Integer id);

    //    查看商品列表
    List<ItemDO> listItems();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Sep 04 20:23:08 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Wed Sep 04 20:23:08 GMT+08:00 2019
     */
    int updateByPrimaryKey(ItemDO record);
}